- netlify.toml
- package-lock.json
- package.json
- webpack.config.js
> Build/ Fix Netlify config

- src/controllers/resources.js
- src/controllers/resources/list/products.js
- src/views/resources/list/products.html
When trying to import a table that have a Boolean attribute, we have something like Boolean("FALSE"), so a result is always TRUE. So i create a function to test it before and the result of this test, we put inside Boolean function, just like Boolean(false), and then will be false
> Mgnr fix edit boolean

- src/controllers/invoices.js
Show only products with quantity, because our client could send wrong product
> fix: items in to invoice with valid quantity

- CHANGELOG.md
- package-lock.json
- package.json
- src/controllers/resources.js
- src/lib/errors.js
- src/script/main.js
- src/views/resources.html
Oi pessoal @matheusgnreis @ThaisChaves ,
Tive que fixar uma coisa na exportação de tabelas (skipar alguns fields pelo nome) e adicionei a opção _Exportar todos_ para listar todos os documentos do resource mas sem todos os campos (parcial).
Preciso que testem isto no https://app-dev.e-com.plus/ por favor antes de darmos merge aqui pra produção, pode ser?
Nozes!
> v1.0.0-alpha.23

- src/controllers/resources/form/settings.js
Besides that, I already put a link to out shopper click and go to store or cms. Before we had only a link to CMS
> fix: set description and show inscription number

- CHANGELOG.md
- package-lock.json
- package.json
- src/controllers/resources/form/products.js
- src/controllers/resources/form/products/render-kit-items.js
- src/controllers/resources/list/products.js
- src/views/inventory.html
- src/views/resources/form/products.html
- Correções pra edição em massa (datas);
- Edição de kit de produtos :tada: :
> v1.0.0-alpha.33

- src/script/main.js
> feat: add link to rules of community

- src/controllers/resources/list/products.js
Check if promo is already working, if so, show price, if not, show base price
> fix: show correct price with promo

- src/controllers/resources/list.js
- src/views/resources/list.html
Add one more card with total items in to order list
> feat: add quantity order card

- CHANGELOG.md
- netlify.toml
- package-lock.json
- package.json
> v1.0.0-alpha.43

- src/controllers/resources/list.js
- src/views/resources/list.html
Inserir essa parte debaixo que estava sendo solicitada, com subtotal, frete e descontos, para avaliarem próximas campanhas de desconto, valor a ser dado para comissão..por isso os 3 cards
> feat: new orders statics in order list

- src/script/main.js
> feat: add some links to support

- src/controllers/resources/list/products.js
Deixei o aviso rodando lá, se não a galera pode achar estranho.
Então, enquanto está editando fica o aviso rodando e o overlay, não permitindo editar nada.
> fix: insert overlay in edit

- scss/components/_forms.scss
Tenho recebido reclamações de que é difícil diferenciar as seleções. Por exemplo, não consegue verificar quais categorias estão selecionadas para retirar a seleção, ou modificar.
Acredito que um check, além da cor que já está dê essa diferenciação esperada.
> chore: insert check in to selected option

- src/controllers/resources/list.js
Set to zero, if all values are zero. So don't show NAN if the result is 0/0
> fix: set zero, if all amounts are zero

- CHANGELOG.md
- package-lock.json
- package.json
- src/controllers/resources/form/products.js
- src/controllers/resources/list.js
- src/script/util.js
- src/views/resources/form/brands.html
- src/views/resources/form/categories.html
- src/views/resources/form/collections.html
- src/views/resources/form/products.html
- src/views/settings.html
> v1.0.0-beta.20

- src/views/shipping-tags.html
> fix: action on http doesnt work anymore

- src/script/main.js
Vou centralizar tudo em mim, quando vier alguém para trabalhar comigo, vou adicionando essa pessoa no ticket.
> Modificar atendente suporte

- src/controllers/invoices.js
I tried to run locally but i had an error with webpack/server, so i just simulate on console browser
> feat(invoice): add total quantity

- CHANGELOG.md
- package-lock.json
- package.json
> v1.0.0-beta.43

- src/controllers/resources/form/orders.js
If there is no registry type, bling or Tiny doesnt send order if client is juridical
> fix(orders) : get registry type from customer

- CHANGELOG.md
- package-lock.json
- package.json
- src/controllers/resources/form/orders.js
> Release v1.0.0-beta.50

- src/controllers/resources/form/carts.js
- src/views/resources/form/carts.html
> feat(carts): add customer information on cart

- src/controllers/resources.js
- src/controllers/resources/form/authentications.js
- src/controllers/resources/list/authentications.js
- src/data/misc/config-lists.json
- src/data/resources/authentications.json
- src/router/routes/resources/form/authentications.js
- src/router/routes/resources/list/authentications.js
- src/script/main.js
- src/views/resources/form/authentications.html
- src/views/resources/list/authentications.html
- src/views/settings.html
Menu
Listagem
Edição
Criação
**DUVIDA: O endpoint /authentications/_id/permissions somente permite método do tipo PATCH, como no caso eu retiro por exemplo o que não quero colocar e envio apenas as permissões que desejo utilizar? Exemplo, crio o usuário e depois coloco as permissões para ele, mas depois quero reduzir, como fazer se temos o PATCH apenas?**
> feat(authentications): add list, edit and create authentications

- src/controllers/resources/form/customers.js
- src/views/resources/form/customers.html
Removendo resumo e criando duas listas, uma com pedidos e outra com pontos.
> chore(customers): change customers page for points and orders

- src/controllers/birth-report.js
- src/router/load-route.js
- src/router/routes/birth-report.js
- src/script/main.js
- src/views/birth-report.html
Quando clica no mês, puxa os dados corretos de cada mês. Por padrão, vem a lista do mês
> feat(customer-report): birthdate report

- src/controllers/resources/form/orders.js
> fix(orders): show same status with different transaction

- src/controllers/resources.js
Por padrão ja existe um filtro pelo input com as opções já carregadas. Por essa quantidade, acredito que resolve e como já existe uma pesquisa no proprio input, facilita para encontrar a categoria desejada
> chore(resources): get more options from categories and brands

- src/controllers/birth-report.js
- src/controllers/cashback.js
- src/controllers/freight-report.js
- src/router/load-route.js
- src/router/routes/birth-report.js
- src/router/routes/freight-report.js
- src/script/main.js
- src/script/util.js
- src/views/freight-report.html
> feat(report): insert freight report

- src/controllers/campaign-report.js
- src/router/load-route.js
- src/router/routes/campaign-report.js
- src/script/main.js
- src/views/campaign-report.html
> feat(campaign-report): campaign report by range date (#410)

- src/controllers/cashback.js
- src/views/cashback.html
> chore(cashback): add cashback clients list for download

- src/controllers/device-report.js
- src/views/device-report.html
Havia esquecido de colocar um sumário com resumo puro e insight de ticket medio por dispostivo que vi em uma plataforma
> chore(device-report): add list with summary

- scss/_main.scss
- src/controllers/coupon-report.js
- src/views/coupon-report.html
Agora ficou bonito o trein:
Responsivo.
VÊ se me ajuda ai, eu coloquei um classlist ali pra deletar os active antigo e inserir os active no que foi clicado, no pagination, mas não está removendo e quando coloquei log no classList apareceu certinho, então não sei o que foi. Pode ser cansaço, mas vê se tem algo ai errado. Funcionou a pesquisa "inteligente" que havia reclamado q nao tinha conseguido e pagination tbm
> fix(coupon-report): parsed date and style

- src/controllers/abandoned-cart.js
- src/router/load-route.js
- src/router/routes/abandoned-cart.js
- src/script/main.js
- src/views/abandoned-cart.html
> feat(abandoned-cart): abandoned cart list

- src/controllers/abandoned-cart.js
> chore: update abandoned cart list with whatsapp link

- src/controllers/resources/form/customers.js
- src/views/resources/form/customers.html
> chore(customers): add option to insert loyalty points

- src/controllers/settings.js
- src/views/settings.html
> feat(settings): add view for list more xml options

- src/controllers/resources/form/collections.js
> feat(collections): use sortable to change position of items in collection

- src/controllers/resources.js
- src/controllers/resources/form/products.js
- src/index.ejs
- src/login/index.js
- src/script/main.js
And remove from regex split multiple variations if has dot or comma
> chore: persist across tabs with local storage autentication v2
